### ISSUE TITLE
  "main": "dist/index.js",   "module": "dist/index.esm.js",  配置文件中这两行需要改变吗，我本地 npm link 读不到

### ISSUE THREAD

**Issue by dongcer** [793338023/components-lib#1]

**Comment by 793338023** [comment]
你可以不改，这只是导入包时默认指向的地址，当然如果你的项目没有dist/index.js，那你可以改成你现在产物的地址，如果访问到你要的资源，看pakage.json的name为包名，我这里是zzc-lib，所以可以zzc-lib/es/index.js这样去访问资源，如果你不清楚，可以先查看下node_modules下你的包存不存在，然后看有什么资源，直接这样访问，如果不想写那么长地址，可以设置main指向你的入口文件，这样就能直接使用包名就能访问到你想要的资源
